//
//  RowAndColumnLabels.swift
//
//  Created by mike davis on 11/5/17.
//  Copyright © 2017 Mike Davis. All rights reserved.
//

import Foundation

// Dummy text for row and column labels.
struct RowAndColumnLabels {
    static let columnZero: [(String, String)] =
        [
            ("", ""),
            ("Brave New World", "Aldous Huxley"),
            ("The Count of Monte Cristo", "Alexandre Dumas"),
            ("The Three Musketeers", "Alexandre Dumas"),
            ("The Color Purple", "Alice Walker"),
            ("Black Beauty", "Anna Sewell"),
            ("The Tenant of Wildfell Hall", "Anne BrontÎ"),
            ("A Clockwork Orange", "Anthony Burgess"),
            ("Barchester Towers", "Anthony Trollope"),
            ("The Adventures of Sherlock Holmes", "Arthur Conan Doyle"),
            ("The Casebook of Sherlock Holmes", "Arthur Conan Doyle"),
            ("The Adventures of Pinocchio", "Carlo Collodi"),
            ("A Tale of Two Cities", "Charles Dickens"),
            ("David Copperfield", "Charles Dickens"),
            ("Great Expectations", "Charles Dickens"),
            ("Oliver Twist", "Charles Dickens"),
            ("The Old Curiosity Shop", "Charles Dickens"),
            ("Westward Ho!", "Charles Kingsley"),
            ("Jane Eyre", "Charlotte BrontÎ"),
            ("Lady Chatterley’s Lover", "D.H. Lawrence"),
            ("Sons and Lovers", "D.H. Lawrence"),
            ("Women in Love", "D.H. Lawrence"),
            ("Sons and Lovers", "D.H. Lawrence"),
            ("Robinson Crusoe", "Daniel Defoe"),
            ("Tales of Mystery and Imagination", "Edgar Allan Poe"),
            ("Wuthering Heights", "Emily BrontÎ"),
            ("A Farewell to Arms", "Ernest Hemingway"),
            ("For Whom the Bell Tolls", "Ernest Hemingway"),
            ("The Sun Also Rises", "Ernest Hemingway"),
            ("Brideshead Revisited", "Evelyn Waugh"),
            ("The Great Gatsby", "F. Scott Fitzgerald"),
            ("Little Lord Fauntleroy", "Frances Hodgson Burnett"),
            ("The Secret Garden", "Frances Hodgson Burnett"),
            ("The Phantom Of Opera", "Gaston Leroux"),
            ("Adam Bede", "George Eliot"),
            ("Middlemarch", "George Eliot"),
            ("The Mill on the Floss", "George Eliot"),
            ("1984", "George Orwell"),
            ("Animal Farm", "George Orwell"),
            ("To Kill a Mockingbird", "Harper Lee"),
            ("Uncle Tom’s Cabin", "Harriet Beecher Stowe"),
            ("Tropic of Cancer", "Henry Miller"),
            ("King Solomon’s Mines", "Henry Rider Haggard"),
            ("Moby Dick", "Herman Melville"),
            ("The Catcher in the Rye", "J.D. Salinger"),
            ("The Lord of the Rings", "J.R.R. Tolkien"),
            ("The Call of the Wild", "Jack London"),
            ("White Fang", "Jack London"),
            ("Go Tell it on the Mountain", "James Baldwin"),
            ("The Last of the Mohicans", "James Fenimore Cooper"),
            ("Ulysses", "James Joyce"),
            ("Pride and Prejudice", "Jane Austen"),
            ("Sense and Sensibility", "Jane Austen"),
            ("Pilgrim’s Progress", "John Bunyan"),
            ("A Separate Peace", "John Knowles"),
            ("Of Mice and Men", "John Steinbeck"),
            ("The Grapes of Wrath", "John Steinbeck"),
            ("Rabbit, Run", "John Updike"),
            ("Gulliver’s Travels", "Jonathan Swift"),
            ("Lord Jim", "Joseph Conrad"),
            ("Catch-22", "Joseph Heller"),
            ("20,000 Leagues Under the Sea", "Jules Verne"),
            ("Around the World in Eighty Days", "Jules Verne"),
            ("The Awakening", "Kate Chopin"),
            ("One Flew Over the Cuckoo’s Nest", "Ken Kesey"),
            ("Cat’s Cradle", "Kurt Vonnegut"),
            ("Slaughterhouse-Five", "Kurt Vonnegut"),
            ("Alice’s Adventures in Wonderland", "Lewis Carroll"),
            ("Little Women", "Louisa May Alcott"),
            ("Gone with the Wind", "Margaret Mitchell"),
            ("Adventures of Huckleberry Finn", "Mark Twain"),
            ("The Adventures of Tom Sawyer", "Mark Twain"),
            ("The Scarlet Letter", "Nathaniel Hawthorne"),
            ("The Naked and the Dead", "Norman Mailer"),
            ("The Importance of Being Earnest", "Oscar Wilde"),
            ("The Picture of Dorian Gray", "Oscar Wilde"),
            ("Lorna Doone", "R. D. Blackmore"),
            ("Invisible Man", "Ralph Ellison"),
            ("Native Son", "Richard Wright"),
            ("Kidnapped", "Robert Louis Stevenson"),
            ("Strange Case of Dr Jekyll and Mr Hyde", "Robert Louis Stevenson"),
            ("Treasure Island", "Robert Louis Stevenson"),
            ("All the King’s Men", "Robert Penn Warren"),
            ("The Satanic Verses", "Salman Rushdie"),
            ("Ivanhoe", "Sir Walter Scott"),
            ("What Katy Did", "Susan Coolidge"),
            ("An American Tragedy", "Theodore Dreiser"),
            ("Far From The Madding Crowd", "Thomas Hardy"),
            ("Beloved", "Toni Morrison"),
            ("Song of Solomon", "Toni Morrison"),
            ("In Cold Blood", "Truman Capote"),
            ("The Jungle", "Upton Sinclair"),
            ("Les MisÈrables", "Victor Hugo"),
            ("The Hunchback of Notre-Dame", "Victor Hugo"),
            ("Lolita", "Vladmir Nabokov"),
            ("The Sketch Book of Geoffrey Crayon, Gent.", "Washington Irving"),
            ("The Moonstone", "Wilkie Collins"),
            ("The Woman in White", "Wilkie Collins"),
            ("As I Lay Dying", "William Faulkner"),
            ("The Lord of the Flies", "William Golding"),
            ("Vanity Fair", "William Makepeace Thackeray"),
            ("Naked Lunch", "William S. Burroughs"),
            ("A Midsummer Night’s Dream", "William Shakespeare"),
            ("All’s Well That Ends Well", "William Shakespeare"),
            ("Anthony and Cleopatra", "William Shakespeare"),
            ("Hamlet", "William Shakespeare"),
            ("King Lear", "William Shakespeare"),
            ("Macbeth", "William Shakespeare"),
            ("Much Ado About Nothing", "William Shakespeare"),
            ("Romeo And Juliet", "William Shakespeare"),
            ("Sophie’s Choice", "William Styron"),
            ("Their Eyes Were Watching God", "Zora Neale Hurston"),
            ]
    static let rowZero =
        [
            "",
            "Library of Congress, United States, Washington D.C.",
            "New York Public Library, United States, New York",
            "Boston Public Library, United States, Boston",
            "New York State Library, United States, Albany, New York",
            "Harvard Library, United States, Cambridge, Massachusetts"
    ]
}
